/* Guitar tunings as data so the set is trivially extensible.
 *
 * A tuning is just an ordered list of strings (lowest → highest), each pinned
 * to a MIDI note number. Frequencies are derived from MIDI against the A4
 * reference, so adding a 7- or 8-string tuning later is a one-line data change
 * (a longer `midi` array) — nothing in the detection or UI hard-codes six
 * strings. The list itself is generated by transposing two canonical shapes
 * (standard E-A-D-G-B-E and Drop-D) down a semitone at a time. */

/** Reference pitch for A4, in Hz. Fixed at concert pitch for now. */
export const A4_HZ = 440;

/** Sharp note names, indexed by MIDI note modulo 12. */
export const NOTE_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'] as const;

export type TuningCategory = 'standard' | 'drop';

export type GuitarString = {
  /** MIDI note number (A4 = 69). */
  midi: number;
  /** Display name, e.g. "E2". */
  name: string;
  /** Target frequency in Hz at A4 = 440. */
  freq: number;
};

export type Tuning = {
  id: string;
  label: string;
  category: TuningCategory;
  /** Lowest → highest string. */
  strings: GuitarString[];
};

/** MIDI note number → frequency in Hz. */
export const midiToFreq = (midi: number): number => A4_HZ * 2 ** ((midi - 69) / 12);

/** MIDI note number → scientific pitch name, e.g. 40 → "E2". */
export const midiToName = (midi: number): string => {
  const name = NOTE_NAMES[((midi % 12) + 12) % 12];
  const octave = Math.floor(midi / 12) - 1;
  return `${name}${octave}`;
};

const makeString = (midi: number): GuitarString => ({
  midi,
  name: midiToName(midi),
  freq: midiToFreq(midi),
});

/** Standard tuning E2 A2 D3 G3 B3 E4 as MIDI. */
const STANDARD_SHAPE = [40, 45, 50, 55, 59, 64];
/** Drop-D shape D2 A2 D3 G3 B3 E4 (low string dropped a whole step). */
const DROP_SHAPE = [38, 45, 50, 55, 59, 64];

/** Pitch-class label for the lowest string of a transposed shape. */
const rootLabel = (lowestMidi: number): string => NOTE_NAMES[((lowestMidi % 12) + 12) % 12];

const transpose = (shape: number[], semitonesDown: number): GuitarString[] =>
  shape.map((m) => makeString(m - semitonesDown));

const idForRoot = (prefix: string, root: string): string =>
  `${prefix}-${root.replace('#', 'sharp').toLowerCase()}`;

/** Standard-shape tunings, low string from E (0) down to A (7 semitones). */
const STANDARD_TUNINGS: Tuning[] = Array.from({ length: 8 }, (_, down) => {
  const strings = transpose(STANDARD_SHAPE, down);
  const root = rootLabel(strings[0].midi);
  return {
    id: idForRoot('standard', root),
    label: down === 0 ? 'E Standard' : `${root} Standard`,
    category: 'standard' as const,
    strings,
  };
});

/** Drop-shape tunings, low string from Drop D (0) down to Drop A (5). */
const DROP_TUNINGS: Tuning[] = Array.from({ length: 6 }, (_, down) => {
  const strings = transpose(DROP_SHAPE, down);
  const root = rootLabel(strings[0].midi);
  return {
    id: idForRoot('drop', root),
    label: `Drop ${root}`,
    category: 'drop' as const,
    strings,
  };
});

export const TUNINGS: readonly Tuning[] = [...STANDARD_TUNINGS, ...DROP_TUNINGS];

export const DEFAULT_TUNING_ID = 'standard-e';

export const tuningById = (id: string): Tuning =>
  TUNINGS.find((t) => t.id === id) ?? TUNINGS[0];
